In [2]:
import numpy as np

In [2]:
x=np.array([3,5])

In [3]:
print(x)

[3 5]


In [4]:
y=np.array([6,9])

In [5]:
print(y)

[6 9]


In [6]:
print(np.greater(x,y))

[False False]


In [7]:
print(np.less(x,y))

[ True  True]


In [8]:
print(np.greater(y,x))

[ True  True]


In [10]:
c=np.arange(30,71)

In [11]:
print(c)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [12]:
a=np.identity(3)

In [13]:
print('3*3 matrix')

3*3 matrix


In [14]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print('3*3 matrix')
print(a)

3*3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
z=np.array([0,21])

In [18]:
print('the orginal matrix')
print(z)

the orginal matrix
[ 0 21]


In [19]:
p=np.arange(0,21)

In [20]:
print('the orginal matrix ')
print(p)

the orginal matrix 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
p[(p>=9)&(p<=15)]*=-1

In [22]:
print(p)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [4]:
d=np.diag([1,2,3,4,5])
print(d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [5]:
print(d.sum())

15


In [6]:
print(sum(d[0]))

1


In [9]:
print(d[0][1]+d[1][1]+d[2][1]+d[3][1]+d[4][1])

2


In [10]:
print(np.sum(d,axis=0))

[1 2 3 4 5]


In [11]:
print(np.sum(d,axis=1))

[1 2 3 4 5]


In [14]:
h=np.array([[1,2,3],[4,5,6]])

In [16]:
print(h)
print(np.sum(h,axis=1))
print(np.sum(h,axis=0))
print(np.sum(h))

[[1 2 3]
 [4 5 6]]
[ 6 15]
[5 7 9]
21


In [17]:
np.savetxt("trial.txt",h)


In [19]:
np.loadtxt("trial.txt")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
 k=np.array([[1,2,3],[4,5,6]])
l=np.array([[7,8,9],[8,5,2]])


In [22]:
print(np.equal(k,l))

[[False False False]
 [False  True False]]


In [23]:
t=np.random.randint(25, size=4)
print(t)

[16 12  9 17]


In [24]:
o=np.array([np.random.randint(25, size=4),np.random.randint(25, size=4),np.random.randint(25, size=4),np.random.randint(25, size=4)])
print(o)

[[ 6  3 10  0]
 [12 13 20 19]
 [ 1  7  5  9]
 [21 18  2 23]]


In [28]:
o[[0,3]]=o[[3,0]]
print(o)

[[21 18  2 23]
 [12 13 20 19]
 [ 1  7  5  9]
 [ 6  3 10  0]]


In [29]:
print(np.multiply(k,l))


[[ 7 16 27]
 [32 25 12]]
