In [1]:
import numpy as np

In [6]:
row=int(input("enter the no of rows:"))

        

enter the no of rows:3


In [24]:
mat1=np.empty((row,row),dtype="int")
print("enter the matrix elements:")
for i in range(0,row):
    for j in range(0,row):
        mat1[i,j]=int(input())

enter the matrix elements:
1
2
3
4
5
6
7
8
9


In [26]:
mat2=np.empty((row,row),dtype="int")
print("enter the matrix elements:")
for i in range(0,row):
    for j in range(0,row):
        mat2[i,j]=int(input())

enter the matrix elements:
6
5
8
9
7
4
1
2
3


In [34]:
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(mat2)

[[6 5 8]
 [9 7 4]
 [1 2 3]]


In [28]:
dot=np.dot(mat1,mat2)
print(dot)

[[ 27  25  25]
 [ 75  67  70]
 [123 109 115]]


In [29]:
tr=np.transpose(mat1)
print(tr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
trace=np.trace(mat1)
print(trace)

15


In [31]:
r=np.linalg.matrix_rank(mat1)
print(r)

2


In [33]:
det=np.linalg.det(mat2)
print(det)

51.0


In [36]:
inverse=np.linalg.inv(mat2)
print(inverse)

[[ 0.25490196  0.01960784 -0.70588235]
 [-0.45098039  0.19607843  0.94117647]
 [ 0.21568627 -0.1372549  -0.05882353]]


In [38]:
eigv,eigvec=np.linalg.eig(mat1)
print("eigen values:",eigv)
print("eigenvectors:",eigvec)

eigen values: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
eigenvectors: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
